"""updates

Revision ID: 5a32831a8bac
Revises: 2636d398626f
Create Date: 2025-09-11 14:42:53.665211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a32831a8bac'
down_revision = '2636d398626f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyer_profile', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_lawyer_profile_user_id', ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyer_profile', schema=None) as batch_op:
        batch_op.drop_constraint('uq_lawyer_profile_user_id', type_='unique')

    # ### end Alembic commands ###
