"""Update

Revision ID: 931fc497b4e2
Revises: 1897e1b0f020
Create Date: 2025-09-13 12:04:41.966467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931fc497b4e2'
down_revision = '1897e1b0f020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('company_name')
        batch_op.drop_column('national_id')

    with op.batch_alter_table('lawyer_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('star_ratings', sa.Float(), nullable=True))
        batch_op.drop_column('bio')
        batch_op.drop_column('license_number')
        batch_op.drop_column('certifications')
        batch_op.drop_column('bar_association')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyer_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bar_association', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('certifications', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('license_number', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('bio', sa.TEXT(), nullable=True))
        batch_op.drop_column('star_ratings')
        batch_op.drop_column('location')
        batch_op.drop_column('description')
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('client_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('national_id', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.DATE(), nullable=True))
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
